### ISSUE TITLE
提一些建议

### ISSUE THREAD

**Issue by chenjia404** [bestZwei/text2img#1]
你先生成图片预览，用户确认后再提交到接口，别生成图片就提交了，测试过程生成大量的垃圾图片
![](https://cdn.img2ipfs.com/ipfs/QmXr2XKVo7Ycs7yLgWACTVksaZHqBaQfTChZpbCnsKWGqN?filename=image.png)
另外可以做成点击输入框自动全选
```
$(':text').focus(function(){
    $(this).one('mouseup', function(event){
        event.preventDefault();
    }).select();
});
```
图片你可以指定一个文件名，这样后面如果优化的时候好处理。
```
const imgSrc = `https://cdn.ipfsscan.io/ipfs/${response.Hash}` + "?filename=text2img.png";
```

**Comment by bestZwei** [comment]
completed
